import 'state.dart';

class Repository {
  List<dynamic> getAll() => _india;

  getLocalByState(String state) => _india
      .map((map) => StateModel.fromJson(map))
      .where((item) => item.state == state)
      .map((item) => item.districts)
      .expand((i) => i)
      .toList();

  List<String> getStates() => _india
      .map((map) => StateModel.fromJson(map))
      .map((item) => item.state)
      .toList();

  List _india = [
    {
      "state": "Andaman-&-Nicobar",
      "districts": ["SOUTH ANDAMAN", "NICOBAR", "NORTH&MIDDLE ANDAMAN"]
    },
    {
      "state": "Andhra-Pradesh",
      "districts": [
        "KURNOOL",
        "ANANTAPUR",
        "SRIKAKULAM",
        "EAST GODAVARI",
        "VISHAKHAPATNAM",
        "KRISHNA",
        "CHITTOOR",
        "WEST GODAVARI",
        "PRAKASAM",
        "NELLORE",
        "CUDDAPAH",
        "GUNTUR",
        "VIZIANAGARAM"
      ]
    },
    {
      "state": "Arunachal-Pradesh",
      "districts": [
        "UPPER SIANG",
        "CHANGLANG",
        "Namsai",
        "PAPUMPARE",
        "DIBANG VALLEY",
        "UPPER SIBANSIRI",
        "LOWER SUBANSIRI",
        "WEST SIANG",
        "WEST KAMENG",
        "LONGDING",
        "EAST KHAMENG",
        "TAWANG",
        "EAST SIANG",
        "LOHIT",
        "TIRAP",
        "LOWER DIBANG VALLEY"
      ]
    },
    {
      "state": "Assam",
      "districts": [
        "Kamrup Metro",
        "KOKRAJHAR",
        "NAGAON",
        "DHUBURI",
        "CHIRANG",
        "BONGAIGAON",
        "KAMRUP",
        "DIBRUGARH",
        "DHEMAJI",
        "SONITPUR",
        "DARRANG",
        "UDALGURI",
        "KARIMGANJ",
        "GOLAGHAT",
        "Charaideo",
        "TINSUKIA",
        "HAILAKANDI",
        "BAKSA",
        "CACHAR",
        "GOALPARA",
        "MAJULI",
        "SIBSAGAR",
        "Hojai",
        "MORIGAON",
        "NALBARI",
        "JORHAT",
        "BARPETA",
        "Biswanath",
        "KARBI ANGLONG",
        "DIMA HASAO",
        "LAKHIMPUR",
        "West Karbi Anglong"
      ]
    },
    {
      "state": "Bihar",
      "districts": [
        "PATNA",
        "VAISHALI",
        "NALANDA",
        "KATIHAR",
        "MADHUBANI",
        "MADHEPURA",
        "ARARIA",
        "ARWAL",
        "SUPAUL",
        "AURANGABAD",
        "WEST CHAMPARAN",
        "MUZAFFARPUR",
        "GOPALGANJ",
        "SHEIKHPURA",
        "NAWADA",
        "EAST CHAMPARAN",
        "SITAMARHI",
        "GAYA",
        "BEGUSARAI",
        "ROHTAS",
        "SARAN",
        "DARBHANGA",
        "KHAGARIA",
        "SAHARSA",
        "SAMASTIPUR",
        "KAIMUR",
        "SEWAN",
        "MUNGER",
        "BHOJPUR",
        "SHEOHAR",
        "KISHANGANJ",
        "PURNIA",
        "JAMUI",
        "JAHANABAD",
        "BANKA",
        "BHAGALPUR",
        "LUCKEESARAI",
        "BUXAR"
      ]
    },
    {
      "state": "Chandigarh",
      "districts": ["CHANDIGARH"]
    },
    {
      "state": "Chhatisgarh",
      "districts": [
        "BILASPUR",
        "RAIGARH",
        "KORBA",
        "JANJGIR",
        "RAIPUR",
        "BEMETARA",
        "RAJNANDGAON",
        "DURG",
        "KONDAGAON",
        "SURAJPUR",
        "BALODABAZAR",
        "KORIA",
        "BALRAMPUR",
        "BALOD",
        "SURGUJA",
        "JASHPUR",
        "BASTAR",
        "MAHASAMUND",
        "DHAMTARI",
        "GARIYABAND",
        "MUNGELI",
        "DANTEWADA",
        "BIJAPUR",
        "KANKER",
        "SUKMA",
        "KAWARDHA"
      ]
    },
    {
      "state": "Delhi",
      "districts": [
        "South West Delhi",
        "Central Delhi",
        "North Delhi",
        "North West Delhi",
        "New Delhi",
        "West Delhi",
        "North East Delhi",
        "South East Delhi",
        "East Delhi",
        "South Delhi",
        "Delhi Shahdara"
      ]
    },
    {
      "state": "Goa",
      "districts": ["SOUTH GOA", "NORTH GOA"]
    },
    {
      "state": "Gujarat",
      "districts": [
        "SURENDRANAGAR",
        "KUTCH",
        "JAMNAGAR",
        "RAJKOT",
        "BHARUCH",
        "BHAVNAGAR",
        "SURAT",
        "AHMEDABAD",
        "DAHOD",
        "TAPI",
        "VADODARA",
        "ARAVALLI",
        "PANCH MAHAL",
        "MAHISAGAR",
        "DEVBHUMI DWARKA",
        "JUNAGADH",
        "MORBI",
        "BANAS KANTHA",
        "KHEDA",
        "NARMADA",
        "MEHSANA",
        "GANDHI NAGAR",
        "SABAR KANTHA",
        "ANAND",
        "PATAN",
        "NAVSARI",
        "VALSAD",
        "BOTAD",
        "AMRELI",
        "CHHOTAUDEPUR",
        "THE DANGS",
        "PORBANDER",
        "GIR SOMNATH"
      ]
    },
    {
      "state": "Haryana",
      "districts": [
        "KAITHAL",
        "REWARI",
        "KARNAL",
        "SONIPAT",
        "HISAR",
        "PALWAL",
        "PANIPAT",
        "ROHTAK",
        "JHAJJAR",
        "SIRSA",
        "YAMUNANAGAR",
        "KURUKSHETRA",
        "JIND",
        "MEWAT",
        "FATEHABAD",
        "FARIDABAD",
        "BHIWANI",
        "MAHENDRAGARH",
        "GURGAON",
        "AMBALA",
        "CHARKI DADRI",
        "PANCHKULA"
      ]
    },
    {
      "state": "Himachal-Pradesh",
      "districts": [
        "KANGRA",
        "HAMIRPUR",
        "MANDI",
        "UNA",
        "BILASPUR",
        "SOLAN",
        "SHIMLA",
        "KULLU",
        "SIRMAUR",
        "CHAMBA",
        "KINNAUR",
        "LAHUL & SPITI"
      ]
    },
    {
      "state": "Jammu-&-Kashmir",
      "districts": [
        "PULWAMA",
        "BADGAM",
        "SRINAGAR",
        "SHOPIAN",
        "KATHUA",
        "UDHAMPUR",
        "JAMMU",
        "BANDIPORA",
        "BARAMULLAH",
        "SAMBA",
        "ANANTNAG",
        "DODA",
        "RAJOURI",
        "KULGAM",
        "POONCH",
        "REASI",
        "KUPWARA",
        "KISHTWAR",
        "RAMBAN",
        "GANDERBAL"
      ]
    },
    {
      "state": "Jharkhand",
      "districts": [
        "DHANBAD",
        "RANCHI",
        "RAMGARH",
        "BOKARO",
        "DEOGHAR",
        "DUMKA",
        "GARHWA",
        "SIMDEGA",
        "CHATRA",
        "LATEHAR",
        "PALAMAU",
        "KODERMA",
        "SAHIBGANJ",
        "HAZARIBAGH",
        "GUMLA",
        "SARAIKELA KHARASAWAN",
        "KHUNTI",
        "GIRIDIH",
        "PAKUR",
        "EAST SINGHBHUM",
        "GODDA",
        "LOHARDAGA",
        "WEST SINGHBHUM",
        "JAMTARA"
      ]
    },
    {
      "state": "Karnataka",
      "districts": [
        "DAVANGERE",
        "BANGALORE",
        "DHARWAD",
        "BANGALORE RURAL",
        "DAKSHIN KANNAD",
        "KOPPAL",
        "UTTAR KANNAD",
        "BELLARY",
        "RAICHUR",
        "MYSORE",
        "HAVERI",
        "TUMKUR",
        "RAMANAGARA",
        "GADAG",
        "BAGALKOT",
        "SHIMOGA",
        "CHIKMAGALUR",
        "BIJAPUR",
        "BIDAR",
        "CHITRADURGA",
        "BELGAUM",
        "MANDYA",
        "YADGIR",
        "GULBARGA",
        "CHIKKABALLAPURA",
        "KOLAR",
        "HASSAN",
        "UDUPI",
        "CHAMRAJNAGAR",
        "KODAGU"
      ]
    },
    {
      "state": "Kerala",
      "districts": [
        "MALAPPURAM",
        "PALAKKAD",
        "ERNAKULAM",
        "KANNUR",
        "KASARAGOD",
        "THIRUVANANTHAPURAM",
        "THRISSUR",
        "PATHANANTHITTA",
        "KOTTAYAM",
        "ALAPPUZHA",
        "KOLLAM",
        "WAYANAD",
        "KOZHIKODE",
        "IDUKKI"
      ]
    },
    {
      "state": "Madhya-Pradesh",
      "districts": [
        "INDORE",
        "NEEMACH",
        "CHHINDWARE",
        "UJJAIN",
        "JABALPUR",
        "SAGAR",
        "SATNA",
        "RATLAM",
        "BHIND",
        "BALAGHAT",
        "KHARGONE",
        "BETUL",
        "RAISEN",
        "SHIVPURI",
        "GWALIOR",
        "BHOPAL",
        "HARDA",
        "DEWAS",
        "JAHBUA",
        "DATIA",
        "ALIRAJPUR",
        "NARSIMHAPUR",
        "RAJGARH",
        "SHEOPUR",
        "PANNA",
        "SEHORE",
        "MORENA",
        "SEONI",
        "BADWANI",
        "DHAR",
        "SINGRAULI",
        "KHANDWA",
        "VIDISHA",
        "KATNI",
        "DAMOH",
        "SIDHI",
        "MANDSAUR",
        "GUNA",
        "SHAJAPUR",
        "MANDLA",
        "AGAR  MALWA",
        "HOSHANGABAD",
        "ASHOKNAGAR",
        "TIKAMGARH",
        "UMARIA",
        "REWA",
        "BURHANPUR",
        "CHHATARPUR",
        "SHAHDOL",
        "ANUPUR",
        "DINDORI"
      ]
    },
    {
      "state": "Maharashtra",
      "districts": [
        "PUNE",
        "NAGPUR",
        "JALNA",
        "NASHIK",
        "BULDHANA",
        "KOLHAPUR",
        "AURANGABAD",
        "SANGLI",
        "SOLAPUR",
        "THANE",
        "PALGHAR",
        "JALGAON",
        "WASHIM",
        "CHANDRAPUR",
        "NANDED",
        "DHULE",
        "AHMADNAGAR",
        "SATARA",
        "WARDHA",
        "AMRAVATI",
        "NANDURBAR",
        "YAVATMAL",
        "PARBHANI",
        "RAIGARH",
        "RATNAGIRI",
        "BHANDARA",
        "GONDIA",
        "LATUR",
        "BID",
        "HINGOLI",
        "OSMANABAD",
        "MUMBAI CITY",
        "GREATER MUMBAI",
        "AKOLA",
        "GADCHIROLI",
        "SINDHUDURG"
      ]
    },
    {
      "state": "Manipur",
      "districts": [
        "EAST IMPHAL",
        "WEST IMPHAL",
        "THOUBAL",
        "KAMJONG",
        "BISHNUPUR",
        "KAKCHING",
        "SENAPATI",
        "JIRIBAM",
        "CHURACHANDPUR",
        "TAMENGLONG",
        "PHERZAWL",
        "KANGPOKPI",
        "UKHRUL",
        "NONEY",
        "CHANDEL",
        "TENGNOUPAL"
      ]
    },
    {
      "state": "Meghalaya",
      "districts": [
        "EAST KHASI HILLS",
        "JAINTIA HILLS",
        "RI BHOI",
        "WEST JAINTIA HILLS",
        "WEST GARO HILLS",
        "NORTH GARO HILLS",
        "EAST JAINTIA HILLS",
        "WEST KHASI HILLS",
        "SOUTHWEST KHASI HILS",
        "EAST GARO HILLS",
        "SOUTH GARO HILLS"
      ]
    },
    {
      "state": "Mizoram",
      "districts": [
        "KOLASIB",
        "AIZAWL",
        "SERCHHIP",
        "MAMIT",
        "SAITUAL",
        "KHAWZAWL",
        "LUNGLEI",
        "HNAHTHIAL",
        "LAWNGTLAI",
        "CHAMPHAI",
        "SAIHA"
      ]
    },
    {
      "state": "Nagaland",
      "districts": [
        "PHEK",
        "DIMAPUR",
        "MON",
        "LONGLENG",
        "TUENSANG",
        "KOHIMA",
        "KIPHERE",
        "PEREN",
        "MOKOKCHUNG",
        "ZUNHEBOTO",
        "WOKHA"
      ]
    },
    {
      "state": "Odisha",
      "districts": [
        "BALESHWAR",
        "JAJPUR",
        "PURI",
        "JHARSUGUDA",
        "KEONJHAR",
        "KORAPUT",
        "RAYAGADA",
        "SONAPUR",
        "NABARANGAPUR",
        "SAMBALPUR",
        "SUNDARGARH",
        "KENDRAPARA",
        "KALAHANDI",
        "BARGARH",
        "ANGUL",
        "MAYURBHANJ",
        "GANJAM",
        "BHADRAK",
        "NUAPARHA",
        "MALKANGIRI",
        "BOLANGIR",
        "CUTTACK",
        "NAYAGARH",
        "GAJAPATI",
        "BOUDH",
        "KHORDHA",
        "JAGATSINGHPUR",
        "DHENKANAL",
        "KANDHAMAL",
        "DEOGARH"
      ]
    },
    {
      "state": "Pondicherry",
      "districts": ["PONDICHERRY", "KARAIKAL", "YANAM", "MAHE"]
    },
    {
      "state": "Punjab",
      "districts": [
        "AMRITSAR",
        "LUDHIANA",
        "MOGA",
        "SANGRUR",
        "PATHANKOT",
        "JALANDHAR",
        "SAS NAGAR",
        "TARN TARAN",
        "KAPURTHALA",
        "HOSHIARPUR",
        "MANSA",
        "FARIDKOT",
        "FAZILKA",
        "RUPNAGAR",
        "BATHINDA",
        "MUKTSAR",
        "FATEHGARH SAHIB",
        "FIROZPUR",
        "BARNALA",
        "SHD BHAGAT SINGH NGR",
        "PATIALA",
        "GURDASPUR"
      ]
    },
    {
      "state": "Rajasthan",
      "districts": [
        "NAGAUR",
        "ALWAR",
        "BANSWARA",
        "JHALAWAR",
        "GANGANAGAR",
        "SIKAR",
        "JAISALMER",
        "TONK",
        "JAIPUR",
        "BHARATPUR",
        "AJMER",
        "SAWAIMADHOPUR",
        "PRATAPGARH",
        "DHAULPUR",
        "CHURU",
        "BARMER",
        "CHITTAURGARH",
        "KARAULI",
        "UDAIPUR",
        "RAJSAMAND",
        "BIKANER",
        "PALI",
        "BHILWARA",
        "DAUSA",
        "DUNGARPUR",
        "JODHPUR",
        "BARAN",
        "BUNDI",
        "KOTA",
        "SIROHI",
        "JHUNJHUNUN",
        "HANUMANGARH",
        "JALOR"
      ]
    },
    {
      "state": "Sikkim",
      "districts": [
        "WEST DISTRICT",
        "EAST DISTRICT",
        "SOUTH DISTRICT",
        "NORTH DISTRICT"
      ]
    },
    {
      "state": "Tamil-Nadu",
      "districts": [
        "DHARMAPURI",
        "ERODE",
        "KANNIYAKUMARI",
        "SALEM",
        "VILUPPURAM",
        "TIRUVALLUR",
        "TIRUPUR",
        "NAMAKKAL",
        "TUTICORIN",
        "VIRUDUNAGAR",
        "TIRUVANNAMALAI",
        "CHENGALPATTU",
        "CHENNAI",
        "THANJAVUR",
        "MADURAI",
        "VELLORE",
        "NAGAPATTINAM",
        "TENKASI",
        "TIRUCHCHIRAPPALLI",
        "COIMBATORE",
        "DINDIGUL",
        "CUDDALORE",
        "PERAMBALUR",
        "RANIPET",
        "KRISHNAGIRI",
        "TIRUNELVELI",
        "KARUR",
        "PUDUKKOTTAI",
        "RAMANATHAPURAM",
        "KANCHIPURAM",
        "SIVAGANGA",
        "TENI",
        "THIRUVARUR",
        "KALLAKURICHI",
        "TIRUPATHUR",
        "ARIYALUR",
        "NILGIRIS"
      ]
    },
    {
      "state": "Telangana",
      "districts": [
        "RANGAREDDI",
        "MEDCHAL MALKAJGIRI",
        "PEDDAPALLI",
        "NAGARKURNOOL",
        "SANGAREDDY",
        "MEHABUBNAGAR",
        "NALGONDA",
        "SIDDIPET",
        "YADADRI BHUVANAGIRI",
        "MEDAK",
        "VIKARABAD",
        "SURYAPET",
        "NIZAMABAD",
        "ADILABAD",
        "MAHABUBABAD",
        "KAMAREDDY",
        "KHAMMAM",
        "JANGAON",
        "KOMRAM BHEEM ASIFABA",
        "BHADRADRI KOTHAGUDEM",
        "WANAPARTHY",
        "WARANGAL RURAL",
        "JAGITIAL",
        "NIRMAL",
        "RAJANNA SIRCILLA",
        "JOGULAMBA GADWAL",
        "WARANGAL",
        "KARIM NAGAR",
        "NARAYANPET",
        "MULUGU",
        "JAYASHANKAR BHUPALPA",
        "HYDERABAD",
        "MANCHERIAL"
      ]
    },
    {
      "state": "Tripura",
      "districts": [
        "UNAKOTI",
        "WEST TRIPURA",
        "DHALAI",
        "GOMATI",
        "SOUTH TRIPURA",
        "SEPAHIJHALA",
        "NORTH TRIPURA",
        "KHOWAI"
      ]
    },
    {
      "state": "Uttarakhand",
      "districts": [
        "UDHAM SINGH NAGAR",
        "RUDRAPRAYAG",
        "CHAMOLI",
        "DEHRADUN",
        "HARIDWAR",
        "PAURI",
        "NAINITAL",
        "TEHRI GARHWAL",
        "CHAMPAWAT",
        "UTTARKASHI",
        "ALMORA",
        "BAGESHWAR",
        "PITHORAGARH"
      ]
    },
    {
      "state": "Uttar-Pradesh",
      "districts": [
        "GORAKHPUR",
        "GONDA",
        "AZAMGARH",
        "RAE BARELI",
        "AGRA",
        "AURAIYA",
        "KANPUR URBAN",
        "MEERUT",
        "BAGHPAT",
        "RAMPUR",
        "BASTI",
        "BUDAUN",
        "PILIBHIT",
        "HATHRAS",
        "FATEHPUR",
        "SANT RAVI NAGAR",
        "CHANDAULI",
        "MUZAFFARNAGAR",
        "BANDA",
        "SAMBHAL",
        "HAMIRPUR",
        "PRATAPGARH",
        "VARANASI",
        "AMETHI/CSM NAGAR",
        "ALLAHABAD",
        "GHAZIPUR",
        "SHAHJAHANPUR",
        "ALIGARH",
        "MAINPURI",
        "MORADABAD",
        "SHRAVASTI",
        "FAIZABAD",
        "HARDOI",
        "GHAZIABAD",
        "JAUNPUR",
        "AMBEDKARNAGAR",
        "FIROZABAD",
        "JALAUN",
        "BAREILLY",
        "SITAPUR",
        "LALITPUR",
        "CHITRAKUT",
        "FARRUKKHABAD",
        "HAPUR",
        "KUSHINAGAR",
        "BALRAMPUR",
        "UNNAO",
        "SONBHADRA",
        "KASHI RAM NAGAR",
        "SULTANPUR",
        "MIRZAPUR",
        "LUCKNOW",
        "LAKHIMPUR",
        "MAHOBA",
        "SIDHARTHNAGAR",
        "ETAWAH",
        "DEORIA",
        "BAHRAICH",
        "ETAH",
        "KANPUR RURAL",
        "GAUTAM BUDH NAGAR",
        "SAHARANPUR",
        "KAUSHAMBI",
        "MATHURA",
        "BARABANKI",
        "BIJNOR",
        "BALLIA",
        "MAHARAJGANJ",
        "SANT KABIR NAGAR",
        "AMROHA",
        "BULANDSHAHR",
        "JHANSI",
        "MAUNATHBHANJAN",
        "SHAMLI",
        "KANNUAJ"
      ]
    },
    {
      "state": "West-Bengal",
      "districts": [
        "BANKURA",
        "HOWRAH",
        "JHARGRAM",
        "MURSHIDABAD",
        "PASCHIM MEDINIPUR",
        "PURBA MEDINIPUR",
        "BIRBHUM",
        "PASCHIM BARDHAMAN",
        "KOLKATA",
        "COOCH BIHAR",
        "JALPAIGURI",
        "UTTAR DINAJPUR",
        "PURBA BARDHAMAN",
        "MALDA",
        "NORTH 24 PARGANAS",
        "SOUTH 24 PARGANAS",
        "NADIA",
        "PURULIA",
        "DAKSHIN DINAJPUR",
        "DARJEELING",
        "HOOGHLY",
        "ALIPURDUAR",
        "KALIMPONG"
      ]
    }
  ];
}
